### ISSUE TITLE
Documentation is offline

### ISSUE THREAD

**Issue by giuseppe4** [creativetimofficial/vue-light-bootstrap-dashboard-pro#11]
Hi,
your documentation is offline at this address: 
http://vuejs.creative-tim.com/vue-light-bootstrap-dashboard-pro/documentation/

It says "not found".

**Comment by cristijora** [comment]
Hi @giuseppe4 
Could you try this link and see if it works?

http://vuejs.creative-tim.com/vue-light-bootstrap-dashboard-pro/documentation/#/getting-started

**Comment by giuseppe4** [comment]
Hi @cristijora, 
now it works!
