### ISSUE TITLE
Table TD overlapping sidebar (z-index override)

### ISSUE THREAD

**Issue by blusol850** [creativetimofficial/vue-light-bootstrap-dashboard-pro#6]
There's an issue with the table data z-index being higher than the sidebar as well as any "fixed" column. to replicate, collapse sidebar, make tables window smaller and mouseover the sidebar menu. you will see the TD is on top of the sidebar. 

it seems related to the **assets/sass/lbd/element_tables.scs**s that does Element UI overrides. Line 8. 

Screenshots:

- [https://drive.google.com/file/d/1Vpnf36kq__PmeI7IzhBChwsjriN5wJfB/view?usp=sharing](url)
- [https://drive.google.com/file/d/19Ax-g0F38DRZjhZVjfpmcLYAz7th9LO7/view?usp=sharing](url)

**Comment by cristijora** [comment]
Hi @blusol850 Unfortunately the screen links are not accessible. If you need to do changes on that css part, feel free to add them. We will also add fixes to them in the next update.
Thanks for reporting!

**Comment by blusol850** [comment]
- [https://drive.google.com/file/d/1Vpnf36kq__PmeI7IzhBChwsjriN5wJfB/view?usp=sharing](https://drive.google.com/file/d/1Vpnf36kq__PmeI7IzhBChwsjriN5wJfB/view?usp=sharing)
- [https://drive.google.com/file/d/19Ax-g0F38DRZjhZVjfpmcLYAz7th9LO7/view?usp=sharing](https://drive.google.com/file/d/19Ax-g0F38DRZjhZVjfpmcLYAz7th9LO7/view?usp=sharing)

Try those links instead.. poor markdown on my end.

one problem I see being a problem is the opacity of the fixed TD elements, showing the rest of the table data behind it.

**Comment by cristijora** [comment]
Will try to figure out some fix for this one @blusol850 Planning to do a version update this week. Does this happen on windows?

**Comment by cristijora** [comment]
@blusol850 Just checked in different browsers and seems to happen on Firefox only. 
Can you try to remove lines 7-10 from `assets/sass/lbd/element/_tables.scss` ?
```css 
.el-table tr{
  z-index: 10;
}
```
I checked into the git history and there is not specific reason this code was added. It was added during the initial commits and most likely is redundant by now. I'd say you could simply remove it and we will remove it as well in the next update (this week)

**Comment by cristijora** [comment]
Fixed in 1.1.0 release. See [Changelog](https://github.com/creativetimofficial/vue-light-bootstrap-dashboard-pro/blob/master/CHANGELOG.md) and [migration guide](http://vuejs.creative-tim.com/vue-light-bootstrap-dashboard-pro/documentation/#/migration_guide). To get the new version go to [Downloads section](https://www.creative-tim.com/downloads) and redownload the product.
